version: '3'
services:
  jenkins: 
    container_name: jenkins
    image: jenkins-custom-image
    user: root
    build: 
      context: docker/jenkins
    volumes:
      - ./jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # Add this line to mount the Docker socket
      - /usr/bin/docker:/usr/bin/docker
      - ./docker/jenkins/casc_configs:/var/jenkins_conf
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_conf
    networks:
      - net
  
  centos7: 
    container_name: centos7
    image: centos7-custom-image
    build: 
      context: docker/centos7
    # working_dir: /usr
    # privileged: true
    # command: bash
    restart: unless-stopped
    networks:
      - net


networks:
  net:
  
