---

- name: Ping all hosts
  ansible.builtin.ping:

- name: Install apt packages
  package:
    name: '{{ packages }}'
    state: present
  retries: 3
  register: installed_packages
  until: installed_packages is succeeded
  become: true

# - name: Ensure /appsdata directory exists
#   ansible.builtin.file:
#     path: /appsdata
#     state: directory
#     owner: hybris
#     group: hybris
#     mode: "0755"
